### ISSUE TITLE
[Proposal] Support from_pretrained

### ISSUE THREAD

**Issue by Hzfinfdu** [OpenMOSS/Language-Model-SAEs#12]
We aim to build a really useful infrastructure for SAE research.

Maybe we need to open source our SAEs with a huggingface-type interface. This may require some sort of cloud service for storage or stuff like that? @dest1n1s 

This has lower priority since this feature is only of use after we trained considerably good SAEs on larger language models.

**Comment by dest1n1s** [comment]
I think HuggingFace itself is well-supported for cloud-serving model checkpoints. We can use similar approach as [Gemma-2b-Residual-Stream-SAEs](https://huggingface.co/jbloom/Gemma-2b-Residual-Stream-SAEs) from [SAELens](https://github.com/jbloomAus/SAELens).
