### ISSUE TITLE
[Proposal] Support DDP for activation generation and SAE training.

### ISSUE THREAD

**Issue by Hzfinfdu** [OpenMOSS/Language-Model-SAEs#14]
A natural approach to faster SAE training is data parallel. Maybe we can just simply use DDP to make 8 copies of the TL model to yield activation and synchronize SAE gradients. This may help accelerate activation gen, which is the speed bottleneck for larger LMs.

This may not work on larger size models, say 70B models. Maybe the ultimate solution is a producer-consumer design pattern. Let's leave this for later.

- [ ] Support DDP

**Comment by alanxmay** [comment]
@Hzfinfdu Hi, thanks for your amazing work. 

Is DDP working now? I tried with 4 GPU, but found process on device (1,2,3) never end.

**Comment by alanxmay** [comment]
BTW, I did some modification to get over a bug in the ddp code.

Error message without modification:
```
...
[rank3]:   File "/home/alan/dev/sae/Language-Model-SAEs/TransformerLens/transformer_lens/components/embed.py", line 34, in forward
[rank3]:     return self.W_E[tokens, :]
[rank3]: RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:0)
```

**Comment by alanxmay** [comment]
@Hzfinfdu Thanks for your replay, my setup is 8*V100(32G) sadly 🤷‍♂️.

**Comment by Hzfinfdu** [comment]
@alanxmay We support TP & DDP now. Documentation is not ready yet XD. We will later upload an example
