### ISSUE TITLE
[Proposal] Improve lm_config.json

### ISSUE THREAD

**Issue by Hzfinfdu** [OpenMOSS/Language-Model-SAEs#22]
What about doing all stuff with relative path? e.g. saving model path in lm_config.json.

I will revisit this later

**Comment by dest1n1s** [comment]
Currently `LanguageModelConfig` accept `model_name` and `model_from_pretrained_path`, do you mean merging these two into one field?

**Comment by Hzfinfdu** [comment]
Sry for the confusion. I meant to save model_from_pretrained_path as relative path instead of absolute one.
