### ISSUE TITLE
How long it takes to train SAEs?

### ISSUE THREAD

**Issue by Spico197** [OpenMOSS/Language-Model-SAEs#58]
Hi there, thanks for the great work~

In [the paper](https://arxiv.org/pdf/2410.20526), you said "SAEs can be trained on an 8B-size model using just a single NVIDIA A100 GPU". I'm wondering how long it takes to train an SAE model with such an online setting.

Thank you very much~

**Comment by Hzfinfdu** [comment]
We trained 8x SAEs with 800M tokens and 32x SAEs with 1.6B tokens. We will add this into the next version of Llama Scope paper, which will be very soon! It depends heavily on your device to determine the exact training time.

Pretrained SAEs should work well for most settings btw.

**Comment by Spico197** [comment]
Thanks for your prompt reply~ I guess the training would converge fast if only 800M or 1.6B tokens were used.  Looking forward to more details in the next version~
