### ISSUE TITLE
Steering not work

### ISSUE THREAD

**Issue by merlinarer** [OpenMOSS/Language-Model-SAEs#61]
Hello, why is the steering hook attached to [```f"{sae.cfg.hook_point_out}.sae.hook_feature_acts",```](https://github.com/OpenMOSS/Language-Model-SAEs/blob/b932639261697c0642d077c05f2cb7e463d058cb/server/app.py#L379), which will not affect the model output.

**Comment by dest1n1s** [comment]
Can you provide more information on why the model output will not be affected? Since the SAEs are attached to the Transformer (i.e. the activation will go through the encoder and decoder of each SAE), modification to the feature activation should result in changes on the model output.

**Comment by merlinarer** [comment]
What I understand is, activation would steered at "sae.hook_feature_acts", while the sae output is added with the reconstrution error (i.e. the model activation in the hooked will remain the same, see [here](https://github.com/OpenMOSS/Language-Model-SAEs/blob/b932639261697c0642d077c05f2cb7e463d058cb/src/lm_saes/circuit/context.py#L22)). I have tried with llama scope weights from hf, and it finally works with following hook (from SAELens tutorials):
```
    def generate_steering_hook(steering: SteeringConfig):
        def steering_hook(tensor: torch.Tensor, hook: HookPoint):
            print(tensor.shape, sae.decoder.weight.shape)
            assert len(tensor.shape) == 3
            if tensor.shape[1] == 1:
                return tensor
            position = tensor.shape[1] - 1
            tensor[:, :position, :] += (steering.steering_value * sae.decoder.weight.T[steering.feature_index])
            return tensor

        sae = get_sae(steering.sae)
        return f"{sae.cfg.hook_point_out}", steering_hook
```

**Comment by dest1n1s** [comment]
Thanks for pointing this out! It seems the current hook point does not affect the final output. We'll fix it soon.

If you’re up for it, a PR will be welcome!

**Comment by merlinarer** [comment]
It seems two ways to steering: 
- Ablate sae. Hook remain the same and using a sae.use_error_term to control whether sae output is added with the reconstrution error or not, which is consistent with current ui.
- Directly add W_dec column to model acts, just as above hook.
I have no idea which one is better, and it is would be great to support both of them. That would need some modification for the ui.

**Comment by dest1n1s** [comment]
I believe the second approach (directly adding the W_dec column to the model acts) would be preferable. The first approach, which involves calculating the reconstruction error without passing through `hook_feature_acts`, seems like it could be more intrusive and require more changes to the existing code. Supporting both approaches might be possible, but the second one appears to align more naturally with the current structure. I'll work on fixing the hook and changing the UI soon.
